server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  admin-paths:
    paths:
      - uri: "/user"
        method: "POST"
      - uri: "/user/savecar/{1}[1-9]+[0-9]*"
        method: "POST"
      - uri: "/user/savebike/{1}[1-9]+[0-9]*"
        method: "POST"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect