spring:
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 500 # Configuración de conexión máxima
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: Cors
              args:
                allowedOrigins: "'*'"
                allowedMethods: "'GET, POST, PUT, DELETE'"
                allowedHeaders: "'*'"
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Path=/email-password/**
          filters:
            - name: Cors
              args:
                allowedOrigins: "'*'"
                allowedMethods: "'GET, POST, PUT, DELETE'"
                allowedHeaders: "'*'"
