server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/email-password/**
        - id: aula-service
          uri: lb://aula-service
          filters:
            - AuthFilter
        - id: docente-service
          uri: lb://docente-service
          filters:
            - AuthFilter
          predicates:
            - Path=/classroom/**
        - id: python-service
          uri: lb://PYTHON-SERVICE
          predicates:
            - Path=/python/**
          filters:
              - StripPrefix=1
